eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      defaultzone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
    
microservice:
  payment-service:
    endpoint:
      uri: http://PAYMENT-SERVICE/payment/doPayment
  order-service:
    endpoint:
      uri: http://ORDER-SERVICE/order/bookOrder    
